ls:
  src:
    .dir: kebab-case
    .scss: kebab-case | regex:_[a-z0-9]+
    .less: kebab-case | regex:_[a-z0-9]+
    .vue: kebab-case | regex:index
    .js: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .spec.ts: kebab-case
    .spec.tsx: kebab-case
    .route.ts: kebab-case
    .type.ts: kebab-case
    .config.js: lowercase
  src/components:
    .dir: kebab-case
ignore:
  - test
  - dist
  - node_modules
  - .*.js
  - .github
  - .git
  - .circleci
  - .vscode
  - .idea
  - .local
  - .husky
