name: Build and Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 7.12.2
      
      - name: install deps
        run: pnpm install
  
      - name: Build
        run: pnpm build:dev

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: dist
